const bb = {boxSizing: 'border-box'}

export default ({
  html: bb,
  body: bb, 
  div: bb,
  article: bb,
  section: bb,
  main: bb,
  footer: bb,
  header: bb,
  form: bb,
  fieldset: bb,
  legend: bb,
  pre: bb,
  code: bb,
  a: bb,
  h1: bb,
  h2: bb,
  h3: bb,
  h4: bb,
  h5: bb,
  h6: bb,
  p: bb,
  ul: bb,
  ol: bb,
  li: bb,
  dl: bb,
  dt: bb,
  dd: bb,
  textarea: bb,
  table: bb,
  td: bb,
  th: bb,
  tr: bb,
  'input[type="email"]': bb,
  'input[type="number"]': bb,
  'input[type="password"]': bb,
  'input[type="tel"]': bb,
  'input[type="text"]': bb,
  'input[type="url"]': bb,
  '.border-box': bb
})
